version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      target: development
      dockerfile: docker/Dockerfile.development
    command: yarn start:dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - toro-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - toro-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=toro

volumes:
  database-volume:

networks:
  toro-network:
    driver: bridge
    name: toro-network
